version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000" # Access your app at http://localhost:8000
        volumes:
            - ./:/var/www/html # Map entire project into container (code sync)
            - ./public/image:/var/www/html/public/image # Persist images folder
        command: php artisan serve --host=0.0.0.0 --port=8000
